// Film Genres
export enum EFilmCategory {
    action = 'action',
    adventure = 'adventure',
    animation = 'animation',
    biography = 'biography',
    comedy = 'comedy',
    crime = 'crime',
    drama = 'drama',
    documentary = 'documentary',
    family = 'family',
    fantasy = 'fantasy',
    feelgood = 'feel good',
    history = 'history',
    horror = 'horror',
    military = 'military',
    musical = 'musical',
    mystery = 'mystery',
    patriotic = 'patriotic',
    political = 'political',
    romance = 'romance',
    scifi = 'sci-fi',
    thriller = 'thriller',
    war = 'war',
}